import { useState } from 'react'
import { LuArrowRight, LuCheck } from 'react-icons/lu'
import { elevatorTypes } from './elevatorsData'

export default function ElevatorTypeSelectorSection() {
  const [activeType, setActiveType] = useState(0)
  const selected = elevatorTypes[activeType]
  return <section id="elevator-types" className="scroll-mt-[104px] bg-[#F5F3EC] px-[clamp(20px,5vw,76px)] py-[clamp(80px,9vw,135px)]"><header className="mx-auto max-w-[800px] text-center"><p className="m-0 text-[11px] font-semibold uppercase tracking-[.2em] text-[#0F2B45]">Find your direction</p><h2 className="mb-0 mt-4 text-[clamp(50px,5.5vw,82px)] font-medium leading-[.98] tracking-[-.045em]">One collection.<br />Made for different journeys.</h2></header><div className="mx-auto mt-10 flex w-fit max-w-full gap-1 overflow-x-auto rounded-full border border-[#EB9B34] bg-white/70 p-1.5" role="tablist">{elevatorTypes.map((item, index) => { const Icon = item.icon; return <button key={item.name} type="button" role="tab" aria-selected={activeType === index} onClick={() => setActiveType(index)} className={`inline-flex min-h-[44px] shrink-0 items-center gap-2 rounded-full px-4 text-[12px] font-medium ${activeType === index ? 'bg-[#0F2B45] text-white' : 'text-[#0F2B45] hover:bg-white'}`}><Icon className="size-4" />{item.name}</button> })}</div><div className="mx-auto mt-12 grid max-w-[1360px] overflow-hidden rounded-[34px] bg-white lg:grid-cols-[1.08fr_.92fr]"><figure className="relative m-0 min-h-[650px] overflow-hidden max-lg:min-h-[520px] max-sm:min-h-[410px]"><img key={selected.image} src={selected.image} alt={selected.name} className="absolute inset-0 size-full object-cover transition-transform duration-700 hover:scale-[1.025]" /></figure><article className="flex flex-col justify-center px-[clamp(28px,6vw,86px)] py-[clamp(60px,8vw,105px)]"><p className="m-0 text-[10px] font-semibold uppercase tracking-[.2em] text-[#0F2B45]">{selected.kicker}</p><h3 className="mb-0 mt-4 text-[clamp(42px,4.5vw,68px)] font-medium leading-[1.01] tracking-[-.04em]">{selected.title}</h3><p className="mb-0 mt-7 text-[16px] leading-[1.72] text-[#0F2B45]">{selected.description}</p><ul className="mt-8 grid gap-3 p-0">{selected.points.map((point) => <li key={point} className="flex items-center gap-3 text-[14px] text-[#0F2B45]"><span className="grid size-6 flex-none place-items-center rounded-full bg-[#EB9B34]"><LuCheck className="size-3.5" /></span>{point}</li>)}</ul><a href="/contact" className="editorial-cta mt-9">Discuss this elevator <span aria-hidden="true"><LuArrowRight /></span></a></article></div></section>
}
