import { LuActivity, LuGauge, LuShieldCheck, LuSmartphone } from 'react-icons/lu'

const featureGroups = [
  [LuShieldCheck, 'Passenger safety', ['UCM device (unintended car movement protection)', 'Overload sensor', 'Child lock', 'Automatic door sensors with child safety', 'Overspeed governor', 'Automatic rescue device (ARD)', 'Emergency evacuation feature', 'Dual electrical-circuit disc brakes', 'Fire-fighting mode']],
  [LuSmartphone, 'Connected access', ['Mobile operation with QR code', 'Emergency push-to-talk', 'Live intercom', 'Live monitoring', 'Mobile-app access control', 'Online error clearance', '24/7 customer care']],
  [LuActivity, 'Smart control', ['IoT lift-usage and motor-health information', 'Microprocessor-based controller with display', 'Energy-saving mode', 'System diagnostics and operating insights']],
  [LuGauge, 'Built for performance', ['Payloads up to 5 tonnes', 'Speeds up to 3 m/s', 'High energy efficiency', 'Low-noise operation', 'Special corrosion-protection coating', 'Self-lubricated bearings', 'High-strength traction sheaves', 'ACOP-certified Mayr disc brakes']],
]

export default function SafetyFeaturesSection() {
  return <section id="safety-features" className="bg-[#0F2B45] px-[clamp(20px,5vw,76px)] py-[clamp(85px,9vw,140px)] text-white"><div className="mx-auto max-w-[1440px]"><header className="grid items-end gap-8 lg:grid-cols-[1.1fr_.9fr]"><div><p className="m-0 text-[11px] font-semibold uppercase tracking-[.2em] text-[#EB9B34]">Safety, intelligence &amp; performance</p><h2 className="mb-0 mt-4 text-[clamp(48px,5.4vw,82px)] font-medium leading-[.96] tracking-[-.045em]">Protection at every level.</h2></div><p className="m-0 max-w-[620px] text-[16px] leading-[1.75] text-white/65">BG Tatva solutions can be configured with advanced safety, connected monitoring and performance features. Final availability depends on the selected model, application and project specification.</p></header><div className="mt-14 grid overflow-hidden rounded-[30px] border border-white/15 md:grid-cols-2 xl:grid-cols-4">{featureGroups.map(([Icon, title, features], groupIndex) => <article key={title} className={`p-[clamp(26px,3vw,42px)] ${groupIndex ? 'border-t border-white/15 md:border-l md:border-t-0' : ''}`}><Icon className="size-7 text-[#EB9B34]" /><h3 className="mb-0 mt-7 text-[24px] font-medium">{title}</h3><ul className="mt-6 grid gap-3 p-0 text-[13px] leading-[1.55] text-white/70">{features.map((feature) => <li key={feature} className="flex gap-3"><span className="mt-[.55em] size-1.5 shrink-0 rounded-full bg-[#EB9B34]" />{feature}</li>)}</ul></article>)}</div><p className="mb-0 mt-6 text-[12px] leading-[1.6] text-white/45">Specifications are project-dependent. Rated load, speed, control, brake and emergency features are confirmed in the final technical proposal.</p></div></section>
}
