import { useState } from 'react'
import { LuArrowRight, LuBuilding2, LuCheck, LuHouse, LuMoveUp, LuRefreshCw, LuShieldCheck, LuSparkles, LuWrench } from 'react-icons/lu'

const elevatorTypes = [
  { name: 'Home Elevators', kicker: 'Effortless movement at home', title: 'Designed around the way you live.', description: 'Quiet, refined vertical mobility for Bengaluru villas, duplexes and private residences, coordinated to feel natural within the architecture.', image: '/images/social-elevator-1.png', icon: LuHouse, points: ['Compact architectural integration', 'Tailored cabin materials and lighting', 'Comfortable, intuitive everyday use'], details: [['Ideal for', 'Villas and private residences'], ['Design character', 'Warm, personal and integrated'], ['Planning focus', 'Space, comfort and interior continuity']] },
  { name: 'Panoramic Elevators', kicker: 'Architecture in motion', title: 'A clearer connection between every level.', description: 'Glass elevators preserve daylight and visual openness while turning movement into a memorable feature for atriums and statement homes.', image: '/images/glass-panoramic-elevator.png', icon: LuMoveUp, points: ['Expansive glass configurations', 'Minimal visual interruption', 'Designed around views and daylight'], details: [['Ideal for', 'Atriums and statement architecture'], ['Design character', 'Transparent, light and expressive'], ['Planning focus', 'Structure, views and heat exposure']] },
  { name: 'Commercial Elevators', kicker: 'Reliable movement at scale', title: 'Performance that supports the building.', description: 'Considered solutions for Bengaluru offices, hospitality and mixed-use developments, planned around traffic, capacity and dependable operation.', image: '/images/elevator-lobby-luxe.png', icon: LuBuilding2, points: ['Planned for frequent daily use', 'Clear, accessible passenger interfaces', 'Coordinated lobby and cabin design'], details: [['Ideal for', 'Offices, hospitality and mixed use'], ['Design character', 'Durable, clear and representative'], ['Planning focus', 'Traffic, capacity and uptime']] },
  { name: 'Modernisation', kicker: 'Renewed performance and character', title: 'Move forward without starting over.', description: 'Targeted upgrades improve reliability, safety, controls, doors, energy performance and cabin design while working with existing infrastructure.', image: '/images/service-modernisation.png', icon: LuRefreshCw, points: ['Condition-led upgrade planning', 'Controls, drives, doors and fixtures', 'Complete cabin and lighting renewal'], details: [['Ideal for', 'Existing and ageing elevator systems'], ['Design character', 'Renewed, efficient and purposeful'], ['Planning focus', 'Condition, downtime and upgrade value']] },
]

const cabinStyles = [
  ['Walnut warmth', 'Rich timber, warm light and bronze details.', '/images/walnut-elevator-cabin.png'],
  ['Ivory calm', 'Soft tonal panels with quiet, even illumination.', '/images/cabin-ivory.png'],
  ['Contemporary steel', 'Crisp metallic surfaces with a precise modern rhythm.', '/images/cabin-steel.png'],
  ['Midnight character', 'Dark finishes, focused lighting and a dramatic presence.', '/images/cabin-black.png'],
]

export function ElevatorsHeroSection() {
  return <section className="grid min-h-screen bg-[#172e3b] text-white lg:grid-cols-[.82fr_1.18fr]"><div className="flex flex-col justify-center px-[clamp(28px,7vw,112px)] pb-20 pt-[150px]"><p className="m-0 text-[11px] font-semibold uppercase tracking-[.2em] text-[#d5b17a]">Bengaluru elevator collection</p><h1 className="mb-0 mt-5 text-[clamp(66px,7.5vw,116px)] font-medium leading-[.84] tracking-[-.06em]">Movement,<br /><em className="font-light text-[#d5b17a]">beautifully</em><br />considered.</h1><p className="mb-0 mt-9 max-w-[560px] text-[17px] leading-[1.72] text-white/70">Elevator systems supplied across Bengaluru and shaped around architecture, performance and the character of every space.</p><a href="#elevator-types" className="mt-9 inline-flex w-fit items-center gap-3 rounded-full bg-[#d5b17a] px-[22px] py-[14px] text-[13px] font-semibold text-[#172e3b]">Explore the collection <span aria-hidden="true"><LuArrowRight /></span></a></div><figure className="relative m-[18px] ml-0 min-h-[720px] overflow-hidden rounded-[36px] max-lg:m-3 max-lg:min-h-[620px]"><img src="/images/social-elevator-5.png" alt="Panoramic glass elevator in a refined Bengaluru residence" className="absolute inset-0 size-full object-cover" /><figcaption className="absolute bottom-6 right-6 max-w-[290px] rounded-[20px] border border-white/25 bg-[#172e3b]/85 p-5 backdrop-blur-xl"><span className="text-[10px] uppercase tracking-[.15em] text-[#d5b17a]">The collection</span><p className="mb-0 mt-2 text-[14px] leading-[1.5] text-white/80">Four distinct directions. One standard of considered design.</p></figcaption></figure></section>
}

export function ElevatorTypeSelectorSection() {
  const [activeType, setActiveType] = useState(0)
  const selected = elevatorTypes[activeType]
  return <section id="elevator-types" className="scroll-mt-[104px] bg-[#f5f3ec] px-[clamp(20px,5vw,76px)] py-[clamp(80px,9vw,135px)]"><header className="mx-auto max-w-[800px] text-center"><p className="m-0 text-[11px] font-semibold uppercase tracking-[.2em] text-[#9c653f]">Find your direction</p><h2 className="mb-0 mt-4 text-[clamp(50px,5.5vw,82px)] font-medium leading-[.98] tracking-[-.045em]">One collection.<br />Made for different journeys.</h2></header><div className="mx-auto mt-10 flex w-fit max-w-full gap-1 overflow-x-auto rounded-full border border-[#c6cdc9] bg-white/70 p-1.5" role="tablist">{elevatorTypes.map((item, index) => { const Icon = item.icon; return <button key={item.name} type="button" role="tab" aria-selected={activeType === index} onClick={() => setActiveType(index)} className={`inline-flex min-h-[44px] shrink-0 items-center gap-2 rounded-full px-4 text-[12px] font-medium ${activeType === index ? 'bg-[#172e3b] text-white' : 'text-[#59666a] hover:bg-white'}`}><Icon className="size-4" />{item.name}</button> })}</div><div className="mx-auto mt-12 grid max-w-[1360px] overflow-hidden rounded-[34px] bg-white lg:grid-cols-[1.08fr_.92fr]"><figure className="relative m-0 min-h-[650px] overflow-hidden max-lg:min-h-[520px] max-sm:min-h-[410px]"><img key={selected.image} src={selected.image} alt={selected.name} className="absolute inset-0 size-full object-cover transition-transform duration-700 hover:scale-[1.025]" /></figure><article className="flex flex-col justify-center px-[clamp(28px,6vw,86px)] py-[clamp(60px,8vw,105px)]"><p className="m-0 text-[10px] font-semibold uppercase tracking-[.2em] text-[#9c653f]">{selected.kicker}</p><h3 className="mb-0 mt-4 text-[clamp(42px,4.5vw,68px)] font-medium leading-[1.01] tracking-[-.04em]">{selected.title}</h3><p className="mb-0 mt-7 text-[16px] leading-[1.72] text-[#59666a]">{selected.description}</p><ul className="mt-8 grid gap-3 p-0">{selected.points.map((point) => <li key={point} className="flex items-center gap-3 text-[14px] text-[#455459]"><span className="grid size-6 flex-none place-items-center rounded-full bg-[#d5b17a]"><LuCheck className="size-3.5" /></span>{point}</li>)}</ul><a href="/contact" className="mt-9 inline-flex w-fit items-center gap-3 rounded-full bg-[#172e3b] px-[22px] py-[14px] text-[13px] font-semibold text-white">Discuss this elevator <span aria-hidden="true"><LuArrowRight /></span></a></article></div></section>
}

export function ElevatorComparisonSection() {
  return <section className="px-[clamp(20px,5vw,76px)] py-[clamp(85px,9vw,140px)]"><header className="mx-auto flex max-w-[1440px] items-end justify-between gap-10 max-lg:flex-col max-lg:items-start"><div><p className="m-0 text-[11px] font-semibold uppercase tracking-[.2em] text-[#9c653f]">Choose with confidence</p><h2 className="mb-0 mt-4 text-[clamp(50px,5vw,78px)] font-medium leading-[.98] tracking-[-.045em]">Understand the difference.</h2></div><p className="m-0 max-w-[520px] text-[16px] leading-[1.7] text-[#59666a]">Every Bengaluru project is unique, but these starting points make it easier to identify the right conversation.</p></header><div className="mx-auto mt-14 grid max-w-[1440px] overflow-hidden rounded-[28px] border border-[#ccd2cf] md:grid-cols-2 xl:grid-cols-4">{elevatorTypes.map((item, index) => { const Icon = item.icon; return <article key={item.name} className={`p-[clamp(28px,4vw,48px)] ${index < 3 ? 'border-b border-[#ccd2cf] xl:border-b-0 xl:border-r' : ''} ${index === 1 ? 'md:border-l xl:border-l-0' : ''}`}><Icon className="size-7 text-[#9c653f]" /><h3 className="mb-0 mt-8 text-[25px] font-medium">{item.name}</h3><div className="mt-8 grid gap-6">{item.details.map(([label, value]) => <div key={label}><span className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#9c653f]">{label}</span><p className="mb-0 mt-1.5 text-[14px] leading-[1.5] text-[#59666a]">{value}</p></div>)}</div></article> })}</div></section>
}

export function CabinStylesSection() {
  return <section className="bg-[#172e3b] px-[clamp(20px,5vw,76px)] py-[clamp(85px,9vw,140px)] text-white"><header className="mx-auto max-w-[800px] text-center"><p className="m-0 text-[11px] font-semibold uppercase tracking-[.2em] text-[#d5b17a]">Cabin design</p><h2 className="mb-0 mt-4 text-[clamp(50px,5.5vw,82px)] font-medium leading-[.98] tracking-[-.045em]">Make the inside<br />feel like it belongs.</h2><p className="mx-auto mb-0 mt-6 max-w-[650px] text-[16px] leading-[1.7] text-white/65">Materials, lighting, controls and proportions come together to create a cabin with its own quiet character.</p></header><div className="mx-auto mt-16 grid max-w-[1440px] gap-5 sm:grid-cols-2 xl:grid-cols-4">{cabinStyles.map(([title, copy, image]) => <article key={title} className="group"><figure className="m-0 h-[470px] overflow-hidden rounded-[24px] bg-[#263c48]"><img src={image} alt={title} loading="lazy" className="size-full object-cover transition-transform duration-700 group-hover:scale-[1.04]" /></figure><h3 className="mb-0 mt-5 text-[23px] font-medium">{title}</h3><p className="mb-0 mt-2 text-[14px] leading-[1.6] text-white/60">{copy}</p></article>)}</div></section>
}

export function ElevatorSupportSection() {
  const services = [[LuSparkles, 'Design coordination', 'Cabin, landing and material decisions aligned with the architecture.'], [LuShieldCheck, 'Safety and clarity', 'Considered operation, interfaces and emergency provisions.'], [LuWrench, 'Installation', 'Clear site readiness, execution, testing and commissioning.'], [LuRefreshCw, 'Local ongoing care', 'Preventive maintenance and responsive support across Bengaluru.']]
  return <><section className="grid bg-[#f5f3ec] lg:grid-cols-2"><figure className="m-0 min-h-[720px] overflow-hidden max-lg:min-h-[560px]"><img src="/images/service-elevator-design.png" alt="Elevator design and planning detail" loading="lazy" className="size-full object-cover" /></figure><div className="flex flex-col justify-center px-[clamp(28px,7vw,110px)] py-[clamp(75px,10vw,140px)]"><p className="m-0 text-[11px] font-semibold uppercase tracking-[.2em] text-[#9c653f]">More than the cabin</p><h2 className="mb-0 mt-4 text-[clamp(48px,5vw,76px)] font-medium leading-[.98] tracking-[-.045em]">A complete elevator experience.</h2><p className="mb-0 mt-7 max-w-[600px] text-[16px] leading-[1.75] text-[#59666a]">From Bengaluru project coordination to long-term service, we manage the decisions that determine how well an elevator works for years.</p><div className="mt-10 grid gap-7 sm:grid-cols-2">{services.map(([Icon, title, copy]) => <article key={title}><Icon className="size-6 text-[#9c653f]" /><h3 className="mb-0 mt-4 text-[19px] font-medium">{title}</h3><p className="mb-0 mt-2 text-[13px] leading-[1.65] text-[#687579]">{copy}</p></article>)}</div></div></section><section className="flex min-h-[540px] flex-col items-center justify-center bg-[#d5b17a] px-6 py-20 text-center"><p className="m-0 text-[11px] font-semibold uppercase tracking-[.2em]">Planning an elevator in Bengaluru?</p><h2 className="mb-0 mt-5 text-[clamp(52px,6.5vw,96px)] font-medium leading-[.94] tracking-[-.05em]">Start with your space.<br />We’ll shape the journey.</h2><a href="/contact" className="mt-9 inline-flex items-center gap-3 rounded-full bg-[#172e3b] px-6 py-[15px] text-[13px] font-semibold text-white">Talk to our team <span aria-hidden="true"><LuArrowRight /></span></a></section></>
}
