import { useState } from 'react'
import { LuArrowRight, LuBuilding2, LuHouse, LuMapPin, LuMoveUp, LuRuler, LuSparkles } from 'react-icons/lu'

const filters = ['All', 'Residential', 'Panoramic', 'Commercial', 'Modernisation']
const projects = [
  ['Lakeview Private Residence', 'North Bengaluru', '2026', 'Panoramic', '/images/glass-panoramic-elevator.png', 'A transparent three-level elevator designed as the light-filled centrepiece of a contemporary home.', '3 stops · Glass cabin · MRL system'],
  ['The Courtyard House', 'Whitefield', '2026', 'Residential', '/images/social-elevator-1.png', 'A warm residential elevator composed around stone, timber and quiet everyday movement.', '4 stops · 6 person · Bespoke cabin'],
  ['Aurelia Business Centre', 'CBD Bengaluru', '2026', 'Commercial', '/images/elevator-lobby-luxe.png', 'A refined twin-elevator arrival experience planned for clarity, capacity and high daily traffic.', '12 stops · Twin bank · Destination controls'],
  ['Walnut House Elevator', 'Indiranagar', '2025', 'Residential', '/images/walnut-elevator-cabin.png', 'A compact home elevator with fluted walnut, warm perimeter light and restrained bronze details.', '3 stops · Timber interior · Compact plan'],
  ['Sky Court Villa', 'Sarjapur', '2025', 'Panoramic', '/images/social-elevator-3.png', 'A cylindrical glass lift that preserves long interior views across a double-height living space.', '4 stops · Curved glass · Scenic travel'],
  ['Meridian Grand Lobby', 'Hebbal', '2025', 'Commercial', '/images/service-elevator-design.png', 'An elegant lobby and cabin language created for a premium mixed-use development.', '16 stops · 13 person · High traffic'],
  ['Heritage Tower Renewal', 'Jayanagar', '2025', 'Modernisation', '/images/service-modernisation.png', 'A phased upgrade improving reliability, controls, door performance and cabin character.', 'Controls · Doors · Cabin renewal'],
  ['Ivory Penthouse', 'Sadashivanagar', '2024', 'Residential', '/images/cabin-ivory.png', 'A calm, tonal cabin continuing the soft material palette of a private penthouse.', '5 stops · Ivory panels · Integrated light'],
  ['Horizon Glass House', 'Devanahalli', '2024', 'Panoramic', '/images/social-elevator-5.png', 'A panoramic home elevator connecting living levels without interrupting daylight or views.', '4 stops · Full glass · Villa specification'],
]

export function ProjectsHeroSection() {
  return <><section className="bg-[#F5F3EC] px-[clamp(20px,5vw,76px)] pb-[clamp(70px,8vw,120px)] pt-[150px]"><div className="mx-auto grid max-w-[1440px] items-end gap-12 lg:grid-cols-[1.2fr_.8fr]"><div><p className="m-0 text-[11px] font-semibold uppercase tracking-[.2em] text-[#0F2B45]">Selected work · Bengaluru</p><h1 className="mb-0 mt-5 max-w-[950px] text-[clamp(64px,8vw,124px)] font-medium leading-[.84] tracking-[-.06em]">Spaces transformed.<br /><em className="font-light text-[#0F2B45]">Journeys elevated.</em></h1></div><div className="pb-2 lg:justify-self-end"><p className="m-0 max-w-[520px] text-[17px] leading-[1.7] text-[#0F2B45]">Explore elevators supplied across Bengaluru, shaped around local homes, commercial spaces and the people who use them.</p><a href="#project-library" className="mt-7 inline-flex items-center gap-3 text-[13px] font-semibold">View all projects <span aria-hidden="true"><LuArrowRight /></span></a></div></div></section><section className="relative min-h-[720px] overflow-hidden bg-[#0F2B45] max-md:min-h-[620px]"><img src="/images/social-elevator-3.png" alt="Panoramic glass elevator in a contemporary Bengaluru residence" className="absolute inset-0 size-full object-cover" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(15,43,69,.84),rgba(15,43,69,.18)_70%)]" /><div className="relative z-10 flex min-h-[720px] max-w-[720px] flex-col justify-end px-[clamp(24px,7vw,110px)] py-[clamp(50px,7vw,100px)] text-white max-md:min-h-[620px]"><p className="m-0 text-[11px] font-semibold uppercase tracking-[.2em] text-[#EB9B34]">Featured · Bengaluru residence</p><h2 className="mb-0 mt-4 text-[clamp(48px,6vw,88px)] font-medium leading-[.94] tracking-[-.045em]">A lift at the heart of the home.</h2><p className="mb-0 mt-6 max-w-[590px] text-[16px] leading-[1.7] text-white/80">A panoramic elevator turns vertical movement into a transparent architectural feature while keeping every level visually connected.</p><div className="mt-8 flex flex-wrap gap-2.5"><span className="rounded-full border border-white/35 px-4 py-2 text-[11px]">4 stops</span><span className="rounded-full border border-white/35 px-4 py-2 text-[11px]">Panoramic glass</span><span className="rounded-full border border-white/35 px-4 py-2 text-[11px]">Private residence</span></div></div></section></>
}

export function ProjectLibrarySection() {
  const [active, setActive] = useState('All')
  const visible = active === 'All' ? projects : projects.filter((project) => project[3] === active)
  return <section id="project-library" className="scroll-mt-[105px] px-[clamp(20px,5vw,76px)] py-[clamp(80px,9vw,135px)]"><header className="mx-auto flex max-w-[1440px] items-end justify-between gap-10 max-lg:flex-col max-lg:items-start"><div><p className="m-0 text-[11px] font-semibold uppercase tracking-[.2em] text-[#0F2B45]">Project library</p><h2 className="mb-0 mt-3 text-[clamp(48px,5vw,76px)] font-medium leading-none tracking-[-.045em]">Built for Bengaluru.</h2></div><div className="flex max-w-full gap-1 overflow-x-auto rounded-full border border-[#F5F3EC] p-1.5" role="tablist">{filters.map((filter) => <button key={filter} type="button" role="tab" aria-selected={active === filter} onClick={() => setActive(filter)} className={`min-h-[40px] shrink-0 rounded-full px-4 text-[12px] font-medium ${active === filter ? 'bg-[#0F2B45] text-white' : 'text-[#0F2B45] hover:bg-[#F5F3EC]'}`}>{filter}</button>)}</div></header><div className="mx-auto mt-14 grid max-w-[1440px] gap-x-7 gap-y-20 md:grid-cols-2 xl:grid-cols-3">{visible.map(([title, location, year, type, image, brief, detail]) => <article key={title} className="group"><figure className="relative m-0 h-[440px] overflow-hidden rounded-[26px] bg-[#F5F3EC] max-sm:h-[380px]"><img src={image} alt={title} loading="lazy" className="size-full object-cover transition-transform duration-700 group-hover:scale-[1.035]" /><span className="absolute left-4 top-4 rounded-full bg-white/90 px-4 py-2 text-[10px] font-semibold uppercase tracking-[.1em] backdrop-blur-md">{type}</span></figure><div className="mt-5 flex justify-between text-[11px] uppercase tracking-[.1em] text-[#0F2B45]"><span className="inline-flex items-center gap-1.5"><LuMapPin />{location}</span><time>{year}</time></div><h3 className="mb-0 mt-4 text-[30px] font-medium leading-[1.12]">{title}</h3><p className="mb-0 mt-3 text-[15px] leading-[1.65] text-[#0F2B45]">{brief}</p><p className="mb-0 mt-5 border-t border-[#F5F3EC] pt-4 text-[11px] font-medium uppercase tracking-[.08em] text-[#0F2B45]">{detail}</p></article>)}</div></section>
}

export function ProjectsApproachSection() {
  const stats = [['150+', 'Completed projects', LuBuilding2], ['10+', 'Years of experience', LuMoveUp], ['120+', 'Bengaluru spaces transformed', LuSparkles]]
  const steps = [['01', 'Discover the space', 'We understand the building, its circulation and the experience the elevator needs to create.', LuHouse], ['02', 'Define the system', 'Capacity, travel, shaft planning and technology are aligned with the architecture.', LuRuler], ['03', 'Design every detail', 'Materials, doors, controls and lighting become one clear design language.', LuSparkles], ['04', 'Install and care', 'Installation, testing, handover and long-term service are managed locally.', LuMoveUp]]
  return <><section className="grid bg-[#0F2B45] text-white md:grid-cols-3">{stats.map(([value, label, Icon], index) => <article key={label} className={`flex min-h-[270px] flex-col justify-center px-[clamp(30px,6vw,90px)] py-14 ${index < 2 ? 'border-b border-white/15 md:border-b-0 md:border-r' : ''}`}><Icon className="size-6 text-[#EB9B34]" /><strong className="mt-7 text-[clamp(46px,5vw,72px)] font-medium leading-none">{value}</strong><span className="mt-3 text-[14px] text-white/65">{label}</span></article>)}</section><section className="grid gap-[clamp(60px,9vw,140px)] bg-[#F5F3EC] px-[clamp(24px,7vw,110px)] py-[clamp(90px,10vw,150px)] lg:grid-cols-[.8fr_1.2fr]"><header className="self-start lg:sticky lg:top-[116px]"><p className="m-0 text-[11px] font-semibold uppercase tracking-[.2em] text-[#0F2B45]">How we deliver</p><h2 className="mb-0 mt-4 text-[clamp(48px,5vw,76px)] font-medium leading-[.98]">From first drawing<br />to final journey.</h2><p className="mb-0 mt-7 max-w-[520px] text-[16px] leading-[1.7] text-[#0F2B45]">A Bengaluru-based team coordinating technical, architectural and service decisions from beginning to end.</p></header><div className="border-t border-[#EB9B34]">{steps.map(([number, title, copy, Icon]) => <article key={number} className="grid gap-6 border-b border-[#EB9B34] py-9 sm:grid-cols-[56px_1fr_auto]"><b className="text-[11px] text-[#0F2B45]">{number}</b><div><h3 className="m-0 text-[25px] font-medium">{title}</h3><p className="mb-0 mt-3 max-w-[620px] text-[14px] leading-[1.7] text-[#0F2B45]">{copy}</p></div><Icon className="size-6 text-[#0F2B45] max-sm:hidden" /></article>)}</div></section></>
}

export function ProjectsCtaSection() {
  return <section className="flex min-h-[540px] flex-col items-center justify-center bg-[#EB9B34] px-6 py-20 text-center"><p className="m-0 text-[11px] font-semibold uppercase tracking-[.2em]">Planning a project in Bengaluru?</p><h2 className="mb-0 mt-5 text-[clamp(52px,6.5vw,96px)] font-medium leading-[.94] tracking-[-.05em]">Let’s create a journey<br />worth remembering.</h2><a href="/contact" className="mt-9 inline-flex items-center gap-3 rounded-full bg-[#0F2B45] px-6 py-[15px] text-[13px] font-semibold text-white">Discuss your project <span aria-hidden="true"><LuArrowRight /></span></a></section>
}
